import {
  Award,
  BarChart2,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  Check,
  CheckCircle,
  Clock,
  Compass,
  Crown,
  Diamond,
  Eye,
  Flag,
  Flame,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Layers,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  Map,
  Medal,
  MessageSquare,
  Mic,
  Phone,
  Rocket,
  Shield,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Catálogo de íconos disponibles en el site builder (subset curado de Lucide). */
export const SITE_ICONS: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  compass: Compass,
  message: MessageSquare,
  trending: TrendingUp,
  globe: Globe,
  map: Map,
  chart: BarChart2,
  lineChart: LineChart,
  users: Users,
  target: Target,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  book: BookOpen,
  graduation: GraduationCap,
  briefcase: Briefcase,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  checkCircle: CheckCircle,
  diamond: Diamond,
  gem: Gem,
  gift: Gift,
  flag: Flag,
  flame: Flame,
  lightbulb: Lightbulb,
  brain: Brain,
  rocket: Rocket,
  shield: Shield,
  lock: Lock,
  mail: Mail,
  phone: Phone,
  mic: Mic,
  smile: Smile,
  sun: Sun,
  eye: Eye,
  layers: Layers,
  zap: Zap,
};

export const SITE_ICON_NAMES = Object.keys(SITE_ICONS);

export function hasSiteIcon(name: unknown): name is string {
  return typeof name === 'string' && name in SITE_ICONS;
}
